org: faisalorg
app: stock-sell-buy
service: stock-sell-buy

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
